FROM dhi.io/maven:3-jdk25-debian13-dev AS builder

WORKDIR /app

COPY . . 

RUN mvn clean package


FROM tomcat:9.0.117-jdk8-corretto-al2

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=builder /app/target/*.war /usr/local/tomcat/webapps/ROOT.war


EXPOSE 8080